Bugfix config using string module instead of str type
Environment
-----------

* Python 3.13
* mkdocs 1.6.1
* live-edit 0.3.1

Error
-----

I get the following python error when trying to configure `mkdocs.yml` live-edit plugin config option `websockets_host`.

```
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
```

The `config_scheme` uses `string` (the `string` module) instead of `str` (the built-in type).

Upstream Reference
------------------

MkDocs [config_options.Type] — the second parameter must be a type in this case.

```python
class Type(Generic[T], OptionallyRequired[T]):
    def run_validation(self, value: object) -> T:
        if not isinstance(value, self._type):  # self._type must be a type
            ...
```

[config_options.Type]: https://github.com/mkdocs/mkdocs/blob/1.6.1/mkdocs/config/config_options.py